# Hostname used for API calls
host: my.rightscale.com

# Common base URL to all API calls

base_url: '/api/acct/71/'
# Use HTTPS?
use_ssl: yes

# Basic auth username if any
username: resat-premium@rightscale.com

# Basic auth password if any
password: Secret123!

# Common request headers for all API calls
headers:
  - name: X-API-VERSION
    value: '1.0'


# Common parameters for all API calls
params:

# Global variables
variables:
  
# hrefs for server templates, rightscripts, ssh key and elastic IPs
# change these values for templates to be tested
  - name:  DB_server_template_href
    value: 'https://my.rightscale.com/api/acct/71/server_templates/47889'
  - name:  ssh_key_href
    value: 'https://my.rightscale.com/api/acct/71/ec2_ssh_keys/118928'
  - name: security_group_href
    value: 'https://my.rightscale.com/clouds/1/ec2_security_groups/159'

# use these parameters for standard 32-bit image
  - name:   thirty_two_bit_image
    value:  'https://my.rightscale.com/clouds/1/ec2_images/36445559'
  - name:   small_instance_size
    value:  'm1.small'
# use these parameters for update to 64-bit image
  - name:   sixty_four_bit_image
    value:  'https://my.rightscale.com/clouds/1/ec2_images/36445558'
  - name:   large_instance_size
    value:  'm1.large'

#cloud variables
  - name:  cloud_id
    value: '1'
  - name:  availability_zone
    value: 'text:us-east-1a'

#deployment and security group config
  - name:  deployment_name
    value: 'Server Template Test - Database MySQL Ubuntu'
    
#deployment inputs
  - name:  db_admin_password
    value: "cred:DBADMIN_PASSWORD"
  - name:  db_admin_user
    value: "cred:DBADMIN_USER"
  - name:  db_backup_lineage
    value: "text:phptest"
  - name:  db_backup_lineage_override
    value: "ignore:$ignore"
  - name:   db_backup_master_hour
    value:  "ignore:$ignore"
  - name:    db_backup_master_minute
    value:   "ignore:$ignore"
  - name:    db_backup_slave_minute
    value:   "ignore:$ignore"
  - name:    db_backup_slave_hour
    value:   "ignore:$ignore"
  - name:  db_replication_password
    value: "cred:DBREPLICATION_PASSWORD"
  - name:  db_replication_user
    value: "cred:DBREPLICATION_USER"
  - name:    db_mysql_datadir_relocate
    value:   "ignore:$ignore"
  - name:    db_mysql_log_bin
    value:   "ignore:$ignore"
  - name:   db_mysql_server_usage
    value:   "ignore:$ignore"
  - name:    db_mysql_tmpdir
    value:   "ignore:$ignore"
  - name:  dns_master_id
    value: "text:4185821"
  - name:  dns_password
    value: "cred:DNSMADEEASY_TEST_PASSWORD"
  - name:  dns_user
    value: "cred:DNSMADEEASY_TEST_USER"
  - name:  dropbox_email
    value: "ignore:$ignore"
  - name:  dropbox_password
    value: "ignore:$ignore"

  - name:  remote_storage_default_account_credentials
    value: "cred:AWS_SECRET_ACCESS_KEY"
  - name:  remote_storage_default_account_id
    value: "cred:AWS_ACCESS_KEY_ID"
  - name:  remote_storage_default_container
    value: "text:resat_test_db"
  - name:  rs_utils_private_ssh_key
    value: "key:rightscale_test"


  - name:   rs_utils_process_list
    value:   "ignore:$ignore"
  - name:   rs_utils_timezone
    value:  "text:UTC"


#files for resat scripts
output: /root/variables.txt
input: /root/variables1.txt
